### ISSUE TITLE
About the text prompt

### ISSUE THREAD

**Issue by ZhiyingDu** [wenyuqing/panacea#11]
Hi, it's really impressive work and it pleasantly surprises me. However, I have a question: Is the text prompt included in the nuScenes Dataset? If not, could you please tell me how to generate these text prompts?

**Comment by wenyuqing** [comment]
Thanks for your attention, the text prompt is generated using GPT to create some template sentences and then combined with class labels from nuScenes (such as car, bicycle, etc.).
