### ISSUE TITLE
What is the role of soft links？

### ISSUE THREAD

**Issue by pisces365** [wenyuqing/panacea#13]
```
ln -s /data/code/StreamPETR/data/nuscenes/data/Dataset/nuScenes/gen-nuscenes-val/ gen-nuscenes-val
ln -s /data/code/StreamPETR/data/nuscenes/data/Dataset/nuScenes/gen-nuscenes-train/ gen-nuscenes-train
```
I know the function of this step is soft linking, but what does it do in the overall system?

**Comment by wenyuqing** [comment]
Hi，because the unzipped files from this zip archive may contain this absolute paths, please ensure that the relative paths for the dataset are correct.

**Comment by wenyuqing** [comment]
If no further problem, I'll close this issue temporally.
