### ISSUE TITLE
The difference between Camera Pose and normal

### ISSUE THREAD

**Issue by YuzhiChen001** [wenyuqing/panacea#16]
Hi, eally a great work!
In your paper, there is"It is noteworthy that the camera pose essentially represents the direction vector", i want to know why not choose normal to control the orientation? What is the difference between them?
Any help would be greatly appreciated.

**Comment by wenyuqing** [comment]
Normal doesn't carry much information by itself.  We introduce camera pose to distinguish the orientations of different viewpoints, hence after normalization, a direction vector is chosen instead of normal.

**Comment by YuzhiChen001** [comment]
thanks！
