### ISSUE TITLE
关于paper细节的一些疑问

### ISSUE THREAD

**Issue by RAYRAYRAYRita** [wenyuqing/panacea#17]
您好，感谢大佬的工作~ 最近正在学习这个方向，读完论文后有一些不明白的点：
1. “This results in layout-controlling images with 19 channels: 10 for depth, 3 for bounding boxes, 3 for road maps, and 3 for camera pose embeddings”，这19个channels的image是否直接作为controlnet的conditional-image convs的输入？ depth、bbox、maps的channels有实际的物理含义吗？
2. unet在两个阶段的训练策略。在其他issue里看到是分不同学习率的，是否方便说明lr、iteraion等参数？
3. controlnet的部分有包含cross-view / cross-frame结构吗？
4. ‘在推理时可以通过text修改车辆颜色’，请问下能否/如何让text的描述定位到具体的instance呢？
期待大佬的回复~

**Comment by wenyuqing** [comment]
非常抱歉回复地这么晚！感谢您对我们工作的关注：1. 这19个channel的图像会直接输入controlnet，里面会有conv layer对channel进行压缩，depth，bbox等都是有实际意义的，可以通过可视化来理解。
2. lr是采用的4e-6 base lr, 其中spatial layer 要小10倍。
3. contronet部分结构和主分支一样，也包含cross-view/frame等。 4. text的修改目前没有引入精确控制的机制，主要还是对整体属性做编辑，如果在text里面指定车的颜色，无法精确定位到instance，我们后续subjectdrive（https://arxiv.org/abs/2403.19438）能对车辆外观做更精确的instance-level的控制，欢迎关注。

**Comment by wenyuqing** [comment]
如果没有后续问题那我暂时关闭啦，推理代码已经放出，欢迎您参考！
