### ISSUE TITLE
关于coarse-grained global control

### ISSUE THREAD

**Issue by w-yibo** [wenyuqing/panacea#2]
首先感谢您非常棒的工作！
关于coarse-grained global control的问题，我的理解是这来自于stable diffusion原始的能力，但是nuscene是没有这类型的数据可以训练的，请问您的模型在训练过程中能否很好地保留stable diffusion的这种能力，比如生成snow，fog之类的场景。

**Comment by wenyuqing** [comment]
您好，感谢关注我们的工作。是的，我们可以很好地保留stable diffusion的理解snow，fog之类标注的能力，并生成对应场景。我们在nuscenes 上finetune并未加上类似天气之类的标签，但我们的训练和测试结果表明，模型没有丢失这种能力。一方面原因是，相比于stable diffusion 预训练，nuscenes的数据量小很多，另一方面原因可能是我们采取的对于不同初始化的参数使用不同学习率的训练策略，帮模型保留了原始的能力。

**Comment by w-yibo** [comment]
非常感谢您的回答！
