### ISSUE TITLE
Do we need to generate the text prompt ourselves

### ISSUE THREAD

**Issue by liuwenlei2018** [wenyuqing/panacea#20]
Hello, I am very interested in your work and thank you very much for opening up the inference code. I am currently reasoning about the code you posted, and when I am reasoning, I am missing a text prompt. Do text prompts need to be generated using GPT themselves, and are there any files that have already been generated. Or maybe I missed some files while downloading data. Thank you.

**Comment by wenyuqing** [comment]
The text prompts are GPT generated templates with annotation informations. 
For example,  "This portrays an urban road panorama, composed from a jointure of six encompassing viewpoint images.  The whole scene contains {} targets, comprising ".
The text prompts are provided in the :[dataset file](https://github.com/wenyuqing/panacea/blob/main/sgm/data/nuscenes_video/nuscenes_datasets_video.py), you can refer to line91-line113.

**Comment by liuwenlei2018** [comment]
Thank you.
