### ISSUE TITLE
About streampetr evaluation

### ISSUE THREAD

**Issue by ppeterpp** [wenyuqing/panacea#22]
Hi, how can we reproduce the evaluation on StreamPETR-S (single frame), using only key frames generated? Please shed some light!

**Comment by wenyuqing** [comment]
Sorry for the late reply, the StreamPETR-s is obtained by closing the temporal propagation, which you may refer to the original StreamPETR paper for more information. I'm sorry that I haven't organized the single-frame-related code yet.

**Comment by ppeterpp** [comment]
Thanks! Does setting queue_length=1 make sense if I only make this change to your 'window' training script?

**Comment by wenyuqing** [comment]
Hello, theoretically it might not be sufficient. Maybe you should check the original implementation in StreamPETR for more specific details.
