### ISSUE TITLE
Different text prompts generate almost the same video generation result.

### ISSUE THREAD

**Issue by Wangyupei** [wenyuqing/panacea#23]
Thanks for your great work. However, in our experiment, we tried different text prompts according to your instruction (the dataset preparation and inference code), the video generation results are almost the same. Is there anything wrong?
﻿

**Comment by Nishad-Sahu** [comment]
Yes I am also facing the same issue. I tried putting hard coded prompts in the FrozenCLIPEmbedder module in sgm/modues/encoders/modules.py but still could not see any difference in the output.

**Comment by wenyuqing** [comment]
Hi，sorry for the lat reply. The current code use the GT image as conditional frame and generate the subsequent video frames for inference, so modifying the text prompt cannot modify the textual attributes well because the subsequent video frames are highly correlated with the conditional frame.
