### ISSUE TITLE
How to assign attribute like rain, fog, snow, night-time with the text prompts ?

### ISSUE THREAD

**Issue by Nishad-Sahu** [wenyuqing/panacea#24]
Hi thanks for making the code open source. I was able to run inferencing with frame length 4 on 2 A6000 GPUs. I wanted to ask how can I assign attributes and custom text prompts while in the inferencing stage? 

For eg. I tried modifying the prompt list in the file sg/data/nuscenes_video/nuscenes_datasets_video.py giving a GPT generated urban night time prompt but it did not make any difference. 

Can you help me out with this ? thankyou

**Comment by wenyuqing** [comment]
The current code use the GT image as conditional frame and generate the subsequent video frames for inference, so modifying the text prompt cannot modify the textual attributes well because the subsequent video frames are highly correlated with the conditional frame.

**Comment by Seq-PKU** [comment]
> The current code use the GT image as conditional frame and generate the subsequent video frames for inference, so modifying the text prompt cannot modify the textual attributes well because the subsequent video frames are highly correlated with the conditional frame.

But in the web page you demonstrate that it can do attribute（rain, fog, snow, night-time） controllable generation . How it's been done?

**Comment by wenyuqing** [comment]
Hi, the video frames generated are largely influenced by the image condition ( eg. the first/last frame), so the attributes controlling should be conducted on the generation of the first stage ( BEV and text guided image generation) first.   But I'm sorry that the code of the first stage is not ready and currently the generated videos are guided by the GT samples, so textual attributes couldn't work well.
