### ISSUE TITLE
Inquiry on gen-nuScenes Dataset Generation Process and Conditions

### ISSUE THREAD

**Issue by lty2226262** [wenyuqing/panacea#27]
Thanks for your amazing work in enhancing the performance of the downstream AV tasks. Could you please elaborate on the process you used to generate your gen-nuScenes dataset? Additionally, what were the text prompts and BEV conditions that guided this generation?

**Comment by wenyuqing** [comment]
Hello, sorry for the late reply, currently only the code of stage two (generate video from given images) is ready, and the text prompts and BEV guidance are provided in the inference pipeline, you can find them in this file [sgm/data/nuscenes_video/nuscenes_datasets_video.py](https://github.com/wenyuqing/panacea/blob/main/sgm/data/nuscenes_video/nuscenes_datasets_video.py)

**Comment by lty2226262** [comment]
Thanks
