### ISSUE TITLE
ImportError: cannot import name 'flash_attn_unpadded_kvpacked_func' from 'flash_attn.flash_attn_interface' 

### ISSUE THREAD

**Issue by JackieHuJunyi** [wenyuqing/panacea#29]

**Comment by hutslib** [comment]
hi, I face the same problem. How do you solve this?
@JackieHuJunyi

**Comment by JackieHuJunyi** [comment]
> hi, I face the same problem. How do you solve this? [@JackieHuJunyi](https://github.com/JackieHuJunyi)

Sorry it's been a long time, I have deleted this code base and I forgot how I did it. 🤦

**Comment by hutslib** [comment]
是flash atten 1.x版本和2.x版本的问题。代码应该是用的1.x

**Comment by wzh506** [comment]
You should use flash-attn==1.0.9
